### ISSUE TITLE
Wrong config?

### ISSUE THREAD

**Issue by Reza702** [ReFraX32/Auto-Clicker-and-Key-Presser#1]
So, I tried using it. The button I want to repeat is Space. But, after it turns on, it doesn't repeat Space, but the alphabet 's'. Some thing wrong here?

**Comment by ReFraX32** [comment]
Thank you for your feedback and for bringing this to my attention. I have identified and fixed the issue with special keys like the Space key in the latest version.

I encourage you to download and test version 1.5.0, which includes these fixes and performance optimizations.
